### ISSUE TITLE
Issue to run a class "only size-1 arrays can be converted to Python scalars"

### ISSUE THREAD

**Issue by intelligent-222** [msu-coinlab/pymoo#155] opened 2021-04-27 04:28 UTC
Hi julesy89,

Thank you for the great package. It seems a functional and complete package to run MOO. I used to use a simple ga package which was good for my single-objective optimization. Given the fact that I am running the EnergyPlus program using python (EPPY package) by using multiprocessing and implementing in Linux HPC computer, the code is being customized to run all these different packages together. 

Recently I found that my research would benefit of executing MOO GA. I realized that your package is one of the best for multi-objective optimization. 

I rewrote my function into the class form as the package required, but when I run the code (not sure if I run it correctly):
    
    problem = MultiNGBT()
    algorithm = NSGA2(pop_size=10)

    res = minimize(problem,
                   algorithm,
                   ("n_gen", 10),
                   verbose=True,
                   seed=1)

    plot = Scatter()
    plot.add(res.F, color="red")
    plot.show()    

 I've got the following error:

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-16-c5976ee2925e> in <module>
          7                ("n_gen", 10),
          8                verbose=True,
    ----> 9                seed=0)
         10 
         11 plot = Scatter()
  
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\pymoo\optimize.py in minimize(problem, algorithm, termination, copy_algorithm, copy_termination, **kwargs)
         83 
         84     # actually execute the algorithm
    ---> 85     res = algorithm.solve()
         86 
         87     # store the deep copied algorithm in the result object
    
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\pymoo\model\algorithm.py in solve(self)
        224 
        225         # call the algorithm to solve the problem
    --> 226         self._solve(self.problem)
        227 
        228         # create the result object based on the current iteration
    
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\pymoo\model\algorithm.py in _solve(self, problem)
        319         # while termination criterion not fulfilled
        320         while self.has_next():
    --> 321             self.next()
        322 
        323     # method that is called each iteration to call some algorithms regularly
    
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\pymoo\model\algorithm.py in next(self)
        241         # call next of the implementation of the algorithm
        242         if not self.is_initialized:
    --> 243             self.initialize()
        244             self.is_initialized = True
        245         else:
    
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\pymoo\model\algorithm.py in initialize(self)
        213 
        214         # call the initialize method of the concrete algorithm implementation
    --> 215         self._initialize()
        216 
        217     def solve(self):
    
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\pymoo\algorithms\genetic_algorithm.py in _initialize(self)
         79 
         80         # then evaluate using the objective function
    ---> 81         self.evaluator.eval(self.problem, pop, algorithm=self)
         82 
         83         # that call is a dummy survival to set attributes that are necessary for the mating selection
    
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\pymoo\model\evaluator.py in eval(self, problem, pop, **kwargs)
         76         # actually evaluate all solutions using the function that can be overwritten
         77         if len(I) > 0:
    ---> 78             self._eval(problem, pop[I], **kwargs)
         79 
         80             # set the feasibility attribute if cv exists
    
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\pymoo\model\evaluator.py in _eval(self, problem, pop, **kwargs)
         95                                return_values_of=self.evaluate_values_of,
         96                                return_as_dictionary=True,
    ---> 97                                **kwargs)
         98 
         99         for key, val in out.items():
    
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\pymoo\model\problem.py in evaluate(self, X, return_values_of, return_as_dictionary, *args, **kwargs)
        284             out = self._evaluate_elementwise(X, calc_gradient, out, *args, **kwargs)
        285         else:
    --> 286             out = self._evaluate_batch(X, calc_gradient, out, *args, **kwargs)
        287 
        288             calc_gradient_of = [key for key, val in out.items()
    
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\pymoo\model\problem.py in _evaluate_batch(self, X, calc_gradient, out, *args, **kwargs)
        383             out["__autograd__"], _ = run_and_trace(self._evaluate, X, *[out])
        384         else:
    --> 385             self._evaluate(X, out, *args, **kwargs)
        386         at_least2d(out)
        387 
    
    <ipython-input-13-317a4e8a9f92> in _evaluate(self, X, out, *args, **kwargs)
        171         Blind_material.Visible_Transmittance=s2
        172 
    --> 173         idf.saveas(path +'/BT_NG_S.idf')
        174         """
        175         #WWr
    
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\eppy\modeleditor.py in saveas(self, filename, lineendings, encoding)
        972         """
        973         self.idfname = filename
    --> 974         self.save(filename, lineendings, encoding)
        975 
        976     def savecopy(self, filename, lineendings="default", encoding="latin-1"):
    
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\eppy\modeleditor.py in save(self, filename, lineendings, encoding)
        928         if filename is None:
        929             filename = self.idfname
    --> 930         s = self.idfstr()
        931         if lineendings == "default":
        932             system = platform.system()
    
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\eppy\modeleditor.py in idfstr(self)
        885             for objname in dtls:
        886                 for obj in self.idfobjects[objname]:
    --> 887                     astr = astr + obj.__repr__()
        888         elif self.outputtype == "nocomment":
        889             return astr
    
    c:\users\mehdi\anaconda3\envs\elective\lib\site-packages\eppy\bunch_subclass.py in __repr__(self)
        362         for val in self.obj:
        363             try:
    --> 364                 value = int(val)
        365                 if value != val:
        366                     value = val
    
    TypeError: only size-1 arrays can be converted to Python scalars

I am pretty sure that I am not an expert in OOP and it may cost me this issue. I greatly appreciate it if you can help me with this since I have a very tight deadline for submitting my paper.

**Comment by intelligent-222** [comment] 2021-05-03 15:06
Please let me know if the issue is not clear or you need any further information.

**Comment by julesy89** [comment] 2021-05-03 15:57
It looks like this command fails `idf.saveas(path +'/BT_NG_S.idf')`. 
This must be your own custom method I think?

**Comment by intelligent-222** [comment] 2021-05-03 17:15
Thank you for the response. I've checked that by running the function independently. assume that I have the function called evaluate (X). I used this function for a single objective and multi variables optimization. the model works adequately. 
Now for multi-objective


    class MultiNGBT(Problem):
    
        def __init__(self):
            super().__init__(n_var=1, n_obj=2, n_constr=0, xl=0, xu=2, type_var=anp.double)
           
    
        def make_options(idf):
            idfversion = idf.idfobjects['version'][0].Version_Identifier.split('.')
            idfversion.extend([0] * (3 - len(idfversion)))
            idfversionstr = '-'.join([str(item) for item in idfversion])
            fname = idf.idfname
            options = {
                'ep_version':idfversionstr,
                'output_prefix':os.path.basename(fname).split('.')[0],
                'output_suffix':'C',
                'output_directory':os.path.dirname(fname),
                'readvars':True,
                'expandobjects':True
                }
        return options


        def _evaluate(self, X, out,*args, **kwargs):
        
            from eppy.modeleditor import IDF
            iddfile = '/EnergyPlusV9-2-0/Energy+.idd'
            IDF.setiddname(iddfile)
            epwfile = path+'/CAN_PQ_Montreal.Intl.AP.716270_CWEC.epw'
        
            a = X
            """
            At this point, the idf file from EnergyPlus being opened and the "a" value will be replaced in the file and 
            will be saved to calculate the objective function.
            """
            idf.saveas(path +'/BT_NG_S.idf')
            """
            Here is the body of the objective function that I deleted to save space
            """
       return (obj1)

as you can see the function works with other packages such as eppy to open a file that is used by EnergyPlus. At this point, the file will be opened and the X value (comes from the optimization algorithm) will be imported into the text file that will be executed by EP. so the next line that you mentioned caused the error is just saving the new file with the new X. 
As I told you before, when I pass a single X through the function it works fine. When I pass X through the class definition as presented above it raises the issue. 


I also was wondering if I can use my evaluate(X) function which is a multivariable (12 variables) and multi-objective (2 objectives) without defining it as a class and run it by functional approach. 

I also can send you my notebook in a private message if you need it. 

Sorry for any inconveniences it may cause you.

**Comment by julesy89** [comment] 2021-05-03 17:23
Try adding `elementwise_evaluation=True`. `X` is in fact the whole population right now and not a single vector.

```
class MultiNGBT(Problem):

    def __init__(self):
        super().__init__(n_var=1, n_obj=2, n_constr=0, xl=0, xu=2, elementwise_evaluation=True, type_var=anp.double)
```

Does this resolve the issue?

**Comment by intelligent-222** [comment] 2021-05-03 19:02
Thank you. I just executed that with one variable and two objectives to see if it works. I will get back to you when it's done.

**Comment by intelligent-222** [comment] 2021-05-04 12:35
Hi Julesy89,

Thank you for your help. The code is working with one variable. If you don't mind, I will try it with multiple variables in HPC and then will close this issue. Otherwise, I can close this issue and open a new one if god forbidden something new came up.

**Comment by julesy89** [comment] 2021-05-04 13:33
Let us keep it open for a few more days. Feel free to close it any time when you think the issue is resolved.

**Closed** 2021-09-07 13:03 UTC
