### ISSUE TITLE
Selection of Best Solution Issue

### ISSUE THREAD

**Issue by intelligent-222** [msu-coinlab/pymoo#181] opened 2021-09-06 14:14 UTC
Hi,

I think my last post was not clear that I didn't get any response. 

I opened a new issue to discuss my issue with the algorithm best solution vs total results. As I mentioned in the previous issue, when I plotted the best solutions of the NSGA II algorithm, the results showed that the suggested best solutions are not the best compare to other results. In the following plot, the algorithm's best solutions are plotted (red dots) along with the total results of the algorithm. It seems that there are multiple points that the other results are better than the selected one. Please let me know if there is any solution for this problem or if there is an option that I can select the best results manually?

Please let me know if you need any further information.

Z_KHZ
![Githubissue](https://user-images.githubusercontent.com/70038498/132230132-6cbf4d26-f2ce-4b1c-a726-092afaade208.png)

My last post:
![Capture](https://user-images.githubusercontent.com/70038498/132232541-57603523-09a9-4144-be0e-656c720768a1.JPG)

**Comment by julesy89** [comment] 2021-09-07 13:01
Duplicate of #176.
Sorry for the late reply.

**Closed** 2021-09-07 13:01 UTC
